Sprint 2
pigarevaoks/middle.messenger.praktikum.yandex pull request #2
Opened 2021-07-23 20:43 UTC by pigarevaoks

2021-07-24 21:52 UTC, avdoshenkov requested changes
Отличная работа! 👍

Пару мелочей поправить и можно будет двигаться дальше

2021-07-24 21:52 UTC, avdoshenkov commented on server.js
> +const PORT = 3000
Здесь можно порт указать таким образом:
```suggestion
const PORT = process.env.PORT || 3000; 
```
Тогда будет возможность брать значение из env-переменных, а уже если там её не окажется, то брать значение по умолчанию

2021-07-24 21:52 UTC, avdoshenkov commented on src/components/chatListItem/chatListItem.tmpl.ts
> +  <div class="chatListItem" id={{{id}}}>
В дальнейшем для этого элемента наверняка появится обработчик клика. Поэтому потом лучше заменить элемент на кнопку или ссылку

2021-07-24 21:52 UTC, avdoshenkov commented on src/components/chatListItem/chatListItem.tmpl.ts
> +    <div class="chatListItem__date">{{{date}}}</div>
Для даты и времени можно использовать специальный тег [`<time>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time)

2021-07-24 21:52 UTC, avdoshenkov commented on src/components/form/form.templ.ts
> +  <section class="form">
Здесь для формы логично будет использовать тег формы. Тогда, например, при нажатии на кнопку с типом `submit` форма будет отправлена силами браузера

2021-07-24 21:52 UTC, avdoshenkov commented on src/utils/HTTPTransport.ts
> +    method?: string
Здесь тоже можно указать тип как `enum`

2021-07-25 06:59 UTC, pigarevaoks commented
спасибо за ревью)

2021-07-25 08:32 UTC, avdoshenkov approved these changes
Отлично! Спасибо за качественную работу 💪

2021-07-26 07:26 UTC, merged