Sprint 3
pigarevaoks/middle.messenger.praktikum.yandex pull request #3
Opened 2021-08-13 21:19 UTC by pigarevaoks

2021-08-19 16:55 UTC, bhoodream requested changes
Шикарный проект, классная реализация, было интересно проводить ревью! Я считаю ты большая молодец! Есть недочеты, как мелкие, так и не очень ;) Было бы круто, если бы ты еще над ними поработала.

Плюс к комментам по коду я столкнулся со следующими проблемами:
- [ ] при регистрации пропускает разные пароли
- [ ] не выводит никаких ошибок от сервера пользователю, увидеть их можно только через консоль
- [ ] в нетлифай все страницы кроме рута выдают 404 ошибку
- [ ] при попытке загрузить аватар происходит ошибка: `reason: "No attached file"`
- [ ] переписка в чатах не работает, сообщения не отправляются, а просто перезагружается страница...
- [ ] поиск по чатам не работает
- [ ] переходы по ссылкам происходят с полной перезагрузкой, хотя по идее должны выполняться через History Api
- [ ] со страницы /settings не выкидывает на главную когда пользователь не авторизован
- [ ] не нашел возможности добавить/удалить пользователя из чата, хотя в ТЗ такой пункт присутствует
- [ ] команда `npm start` подымает проект, но по ссылке (http://localhost:3000/) сервер падает с ошибкой: `ReferenceError: path is not defined`
- [ ] линтинг, в частности скриптов (`npm run lint:js`) падает с ошибками: `✖ 38 problems (37 errors, 1 warning)`

2021-08-19 16:55 UTC, bhoodream commented on .gitignore
> +package-lock.json
`package-lock.json` не нужно игнорировать, это важный файл, который позволяет фиксировать установленные зависимости для стабильной работы проекта

Здесь можно посмотреть зачем он был когда-то создан https://nodejs.dev/learn/the-package-lock-json-file

2021-08-19 16:55 UTC, bhoodream commented on .prettierrc
> +    "trailingComma": "none",
Рекомендуется использовать `trailingComma`
Несколько причин почему https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

2021-08-19 16:55 UTC, bhoodream commented on package.json
> +    "lint-staged": {
`lint-staged` не работает на хуке `pre-commit`, потому что хаски настроены некорректно 

Попробуй посмотреть доку по настройке https://github.com/typicode/husky

2021-08-19 16:55 UTC, bhoodream commented on src/components/avatar/avatar.less
> +        transition: all 0.2s ease;
Насчет `transition: all`, когда так скопом вешаешь переходы, это может привести к незапланированным эффектам при изменении ширины, цвета и тд.

Также для переходов оптимизировано очень мыло свойств, по сути это только `transform` и `opacity`.  Если тебе важна плавность твоих анимаций, только в крайнем случае анимируй что-то кроме этих свойств.

Небольшая памятка по анимациям в вебе https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance?hl=ru

2021-08-19 16:55 UTC, bhoodream commented on src/components/avatar/index.ts
> +// import {IUser, IAvatartData} from 'api/user/models'
Комментики надо подчищать :)

2021-08-19 16:55 UTC, bhoodream commented on src/components/backButton/backButton.tmpl.ts
> +<button class="backButton" type="${EButtonType.Button}" name="back" id="backButton">
Если нет необходимости ставить `id` на элемент, лучше этого не делать, как в случае с кнопкой `backButton`. На странице не должно быть элементов с одинаковыми `id`. 

Обсуждения на тему https://softwareengineering.stackexchange.com/questions/127178/two-html-elements-with-same-id-attribute-how-bad-is-it-really

2021-08-19 16:55 UTC, bhoodream commented on src/components/profileInput/index.ts
> +                    inputValidation(event)
По идее валидация на `focus` событии не нужна, потому что пользователь даже еще не успел ничего ввести, а ты уже ему говоришь что он где то ошибся.

2021-08-19 16:55 UTC, bhoodream commented on src/components/profileInput/profileInput.templ.ts
> +        disabled={{disabled}}
`disabled` атрибут является булевым (да/нет) и не нуждается ни в каком значении

http://htmlbook.ru/html/input/disabled

2021-08-19 16:55 UTC, bhoodream commented on src/components/searchInput/searchInput.tmpl.ts
> +        id="{{ name }}"
Я уже про `id` говорил, но хочу еще раз заострить на этом внимание. Лучше все ненужные `id` убрать вообще отовсюду, пока в них не появится реальной необходимости.

Страница с двумя одинаковыми `id` является некорректной, не усложняй себе жизнь ;)

2021-08-19 16:55 UTC, bhoodream commented on src/index.html
> +        <div id="app" class="app"></div>
Вот здесь вот `id` действительно уместен, потому что единственный на все приложение элемент. :)

2021-08-19 16:55 UTC, bhoodream commented on src/modules/HTTPTransport/enums.ts
> +export enum METHOD {
`enum` это только структура для хранения данных, не думаю что стоит в именовании файлов завязываться на такие вещи. Мне кажется было бы все таки лучше назвать не `enums.ts`, а более стандартным названием `constants.ts`.

2021-08-31 14:29 UTC, bhoodream commented
Привет, а ты куда пропала? Почему работу не отправляешь повторно?

2021-11-13 09:11 UTC, pigarevaoks commented
> Привет, а ты куда пропала? Почему работу не отправляешь повторно?

Прости, что так поздно отвечаю, я брала академ из за семейных обстоятельств. Я добила правки, можно проверять)

2021-11-13 10:16 UTC, bhoodream approved these changes
Спасибо за правки! Почти все моменты о которых я говорил поправлены, что очень круто :) От меня АПРУВ, желаю удачи на будущих спринтах!

P.S. Пара проблем, которые остались:
- [ ] в netlify, при перезагрузке страницы так и остались ошибки 404... корректно открывается только рут `/`
- [ ] есть одна ошибка по `eslint`: `/middle.messenger.praktikum.yandex/src/modules/HTTPTransport/tests/HTTPTransport.spec.ts   2:14  error    Require statement not part of import statement`

2021-11-13 10:16 UTC, bhoodream commented on .gitignore
> +*.lock
Этот файл игнорировать не надо, он нам нужен, так как в нем необходимая для работоспособности проекта информация.

https://habr.com/ru/company/domclick/blog/513130/

2021-11-13 10:16 UTC, bhoodream commented on package.json
> +    "lint-staged": {
Это было актуально для второго спринта, на 3 я это по ошибке проверил :) Но он все же не работает, учти ;)

2021-11-14 10:02 UTC, merged